swagger: "2.0"
info:
  description: "API documentation for the Gnucash Rest API (https://github.com/loftx/gnucash-rest) used to provide Python based REST framework for the Gnucash accounting application (https://www.gnucash.org/)"
  version: "Alpha"
  title: "Gnucash Rest API"
  contact:
    email: "dev@loftx.co.uk"
  license:
    name: "GNU GPLv3"
    url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
#host: ""
#basePath: ""
tags:
- name: "customers"
  #description: ""
schemes:
- "http"
paths:
  /customers/{customerId}:
    get:
      tags:
      - "customers"
      summary: "Find customer by ID"
      description: "Returns a single customer"
      produces:
      - "application/json"
      parameters:
      - name: "customerId"
        in: "path"
        description: "ID of customer to return"
        required: true
        type: "integer"
        #format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Customer"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Customer not found"
definitions:
  Customer:
    type: "object"
    required:
    - "name"
    - "address"
    properties:
      shipping_address:
        $ref: "#/definitions/Address"
      name:
        type: "string"
      credit:
        type: "integer" # is this a double/enum
      notes:
        type: "string"
      tax_table_override:
        type: "boolean" # does this work
      discount:
        type: "integer" # might be an enum?
      address:
        $ref: "#/definitions/Address"
      active:
        type: "boolean"
      guid:
        type: "string"
      id:
        type: "string"
      tax_included:
        type: "integer"  # might be an enum?
  Address:
      type: "object"
      required:
      - "line_1"
      properties:
        fax:
          type: "string"
        name:
          type: "string"
        email:
          type: "string"
        photo:
          type: "string"
        line_1:
          type: "string"
        line_2:
          type: "string"
        line_3:
          type: "string"
        line_4:
          type: "string"
externalDocs:
  description: "Full documentation and code on Github"
  url: "https://github.com/loftx/gnucash-rest"